export { default as Dashboard } from './Dashboard'
export { default as Analytics } from './Analytics'
export { default as Investments } from './Investments'
export { default as Settings } from './Settings'
export { default as Wallet } from './Wallet'
export { default as WatchLists } from './WatchLists'